language: php
sudo: false

# disable the default submodule logic
git:
  submodules: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

# testing https://github.com/box-project/box2/blob/gh-pages/installer.php#L48-L57
script: |
    php -r '$phar = new ReflectionExtension("phar");var_dump($phar->getVersion());'
    curl -LSs https://box-project.github.io/box2/installer.php | php

# vim:ts=2:sw=2:et
