name: build-image

on:
  push:
    paths:
      - ".github/workflows/build-image.yml"
      - "bin/releng/*"
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/${{ github.event.repository.full_name }}:build-image

# vim:ft=yaml:et:ts=2:sw=2
