name: "ci"

on:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - "*"
    tags:
      - snapshot
      - v*
  pull_request:

jobs:
  ci:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04

    steps:
      - name: Seed database
        run: |
          echo hi

# vim:ft=yaml:et:ts=2:sw=2
