name: "Build release"
on:
  workflow_run:
    workflows:
      - "ci"
    branches:
      - "*"
    types:
      - completed

jobs:
  release:
    name: Build release
    runs-on: ubuntu-20.04
    steps:
      - name: Build release tarball
        run: |
          echo  ${{ github.event.workflow_run.conclusion }}

# vim:ft=yaml:et:ts=2:sw=2
